server:
  port: 9000

spring:
  application:
    name: lvtumall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.105.108.186:3306/lvtumall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 39.105.108.186:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 39.105.108.186:8858

  redis:
    host: 39.105.108.186
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'