spring:
  cloud:

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 39.105.108.186:8858

    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=uri,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=uri,qq
#        - id: lvtumall_host_route
#          uri: lb://lvtumall-product
#          predicates:
#            - Host=**.lvtumall.com

        - id: product_route
          uri: lb://lvtumall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://lvtumall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://lvtumall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://lvtumall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://lvtumall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://lvtumall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: lvtumall_host_route
          uri: lb://lvtumall-product
          predicates:
            - Host=lvtumall.com,item.lvtumall.com

        - id: lvtumall_search_route
          uri: lb://lvtumall-search
          predicates:
            - Host=search.lvtumall.com

        - id: lvtumall_auth_route
          uri: lb://lvtumall-auth-server
          predicates:
            - Host=auth.lvtumall.com

        - id: lvtumall_cart_route
          uri: lb://lvtumall-cart
          predicates:
            - Host=cart.lvtumall.com

        - id: lvtumall_order_route
          uri: lb://lvtumall-order
          predicates:
            - Host=order.lvtumall.com

        - id: lvtumall_member_route
          uri: lb://lvtumall-member
          predicates:
            - Host=member.lvtumall.com

        - id: lvtumall_seckill_route
          uri: lb://lvtumall-seckill
          predicates:
            - Host=seckill.lvtumall.com



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree