spring:
  cloud:
    nacos:
      discovery:
        server-addr:  39.105.108.186:8848


    alicloud:
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        appcode: 7438617c5b404226bda011152e580c6c


  application:
    name: lvtumall-third-party

server:
  port: 30000