server:
  port: 40000


spring:
  application:
    name: lvtumall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 39.105.108.186:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 39.105.108.186:8858

  redis:
    port: 6379
    host: 39.105.108.186

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true


  session:
    store-type: redis

#配置线程池
lvtumall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


