server:
  port: 12000

spring:
  application:
    name: lvtumall-search
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.108.186:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 39.105.108.186:8858

  redis:
    host: 39.105.108.186
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  thymeleaf:
    cache: false

  session:
    store-type: redis

logging:
  level:
    com.future.lvtumall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
